name: Tests unitaires de l'app

on:
  push

jobs:
  Tests-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12, 14, 16]
    steps: 
      - name: Récupération du repo
        uses: actions/checkout@v3
      - name: j'effectue des tests
        id: test
        run: exit 1
      - name: Je créée un ticket
        if: failure()
        uses: actions-ecosystem/action-create-issue@v1
        with:
          title: ${{ steps.test.name }}
          body: |
            ## A faire au plus vite
            - [ ] Revoir le code
            - [ ] Revoir le process 
          