name: Tests unitaires de l'app

on:
  push

env:
  APP_VERSION: "1.0.0"

jobs:
  Tests-app:
    runs-on: ubuntu-latest
    steps: 
      - name: Récupération du repo
        uses: actions/checkout@v3
      # - name: j'effectue des tests
      #   id: test
      #   run: exit 1
      # - name: Je créée un ticket
      #   if: failure()
      #   uses: actions-ecosystem/action-create-issue@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     title: Echec test unitaire
      #     body: |
      #       ## A faire au plus vite
      #       - [ ] Revoir le code
      #       - [ ] Revoir le process 

  Build-app:
    runs-on: ubuntu-latest
    steps: 
      - name: Récupération du repo
        uses: actions/checkout@v3
      - name: Installation de QEMU
        uses: docker/setup-quemu-action@v1
      - name: Installation de Docker BuildX
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login au Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: $ {{ secrets.DOCKER_USERNAME }}/weather:$APP_VERSION